import "./globals.css";
import Headerof from "../components/Header";
import { Votestore } from "@/store/Dvotingstore";

export const metadata = {
  title: "A decentralized voting system",
  description: "Generated by saba ali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-700">
        <Votestore>
          <Headerof />
          <main>{children}</main>
        </Votestore>
      </body>
    </html>
  );
}
